destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/vega-pdf"
port: 4011
output: pdf
product: vega
print_title: Vega tutorial
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: vega_sidebar
